---
title: JPE Replication Report
date: today
number-sections: true
format:
  pdf: default
---

# Paper Identification

|  |   |
| ---  |  -------|
| ID  |  {{< var paper_id >}} |
| Author  |  {{< var author >}} |
| Title  |  {{< var title >}} |
| Iteration |  {{< var round >}} |

Some useful information up front:

- [JPE Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy)
- [Step by step guidance from Data Editor for Authors](https://jpedataeditor.github.io/) 
- [Template README](https://social-science-data-editors.github.io/template_README/)

# Summary

In assessing compliance with our [Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy), our reproducibility team has identified the following issues, which we ask you to address:

1. Data Editor's first point.
2. Data Editor's second point.

# General


> {REPLICATOR} Check off the following sections/elements that you find in either the README provided by the authors, or in the authors' online appendix (rare).

- [X] Data Availability and Provenance Statements
  - [X] Statement about Rights - Part 1: Right to use the data (e.g. *did the authors lawfully obtain the data*)
  - [X] Statement about Rights - Part 2: Right to publish the data (e.g. *are human subjects involved and did permission been granted to publish their data?*)
  - [ ] License for Data (optional, but recommended)
  - [X] Details on each Data Source
- [X] Dataset list
- [X] Computational requirements
  - [X] Software Requirements
  - [X] Controlled Randomness (as necessary)
  - [ ] Memory, Runtime, and Storage Requirements
- [X] Description of programs/code
  - [X] License for Code (Optional, but recommended) 
- [X] List of tables and programs
- [ ] References (Optional, but recommended) 


# High-level Description of Research Project

*This research project...*

- [X] uses observational data.
- [ ] uses *confidential* observational data.
- [ ] uses data generated via experiment or trial by the authors (in field or lab).
  - [ ] For lab experiments: The code to implement the experimental protocol (z-Tree, o-Tree etc) is included in the package.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF document outlining the design of the experiment, including information on the selection and eligibility of participants is included.
  - [ ] A PDF copy of the instructions given to participants in both original language and an English translation is included.
- [X] uses data generated via survey by the authors (in field or online)
  - [ ] The programs used to administer the survey (e.g. qualtrics survey file) are included.
  - [X] A PDF copy of IRB approval is contained in the package.
  - [X] A PDF of the original questionaire(s) and information on the selection and eligibility of participants is included.
- [ ] is a simulation study: the data are generated by an algorithm.
- [ ] is a numerical illustration: no data are used but code is used to produce illustrative output (tables, figures)


# Data description

## Data Sources

| file/name            | public | private | shared with us | DOI/URL | Access described| cited readme | cited paper |
| ----                 | ---    | ---     | ---     | ---     | ---             | ----         | ----        | 
| recruit_baseline_roster_TC.dta | no    | yes      | yes     | -     | Survey data              | yes          | yes         |
| recruitment_baseline.dta | no    | yes      | yes     | -     | Survey data              | yes          | yes         |
| recruitment_baseline_2nd.dta | no    | yes      | yes     | -     | Survey data              | yes          | yes         |
| first_movers_analysis.dta | no    | yes      | yes     | -     | Survey data              | yes          | yes         |
| TC_cleaned.dta | no    | yes      | yes     | -     | Survey data             | yes          | yes         |
| TC_cleaned_2nd.dta | no    | yes      | yes     | -     | Survey data              | yes          | yes         |
| TC_first_movers_merged.dta | no    | yes      | yes     | -     | Survey data              | yes          | yes         |
| attrition.dta | no    | yes      | yes     | -     | Survey data              | yes          | yes         |
| extremity_first_movers_cleaned.dta | no    | yes      | yes     | -     | Survey data              | yes          | yes         |
| extremity_TC_merged.dta | no    | yes      | yes     | -     | Survey data              | yes          | yes         |
| anes_full.csv | yes    | no      | yes     | -     | -              | yes          | yes         |
| anes_full_inperson.csv         | yes    | no      | yes       | www.electionstudies.org       | yes              | yes           | yes         |


# Requirements 

- [X] README is in TXT, MD, or PDF format
- [ ] README is accessible at the root of the package (not inside a folder) - [ ] Title conforms to guidance (starts with "Data and Code for: Title of Paper" or "Code for: Title of Paper", is properly capitalized)
- [x] Authors (with affiliations) are listed in the same order as on the paper

> {REQUIRED} Please review the title of the deposit as per our guidelines.


## Stated Requirements

- [ ] No requirements specified
- [X] Software Requirements specified as follows:
  - Stata MP 18.0
  - Python
- [ ] Computational Requirements specified as follows:
- [X] Time Requirements specified as follows:
  - Length of necessary computation (hours, weeks, etc.)

- [ ] Requirements are complete.

For missing requirements, see the list of required changes in @sec-findings

# Analyzing Data and Code Files

{{< include generated/report-pii.md >}}

{{< include generated/report-file-paths.md >}}

{{< include generated/report-duplicates.md >}}

{{< include generated/report-zero-files.md >}}

{{< include generated/report-large-files.md >}}



## Code description

{{< include generated/report-cloc.md >}}


- [X] The replication package contains a "main" or "master" file(s) which calls all other auxiliary programs.

> NOTE: In-text numbers that reference numbers in tables do not need to be listed. Only in-text numbers that correspond to no table or figure need to be listed.

## Computing Environment of the Replicator

- SSPCloud instance, RStudio image with 32Gb of memory running Debian 13.1 on Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz with 18 cores

- Stata/MP 18.0

# Replication

- Installed packages as required (see README #5.1)

- Ran `silence_master.do` as per README, got an error while running sub-script `Figure D4.do`:

```bash
. splitvallabels treat, length(2)
command splitvallabels is unrecognized
r(199);
```

- Package `libutil2`, which is supposed to have `splitvallabels`, does not actually provide the command. I could not find a suitable replacement. Perhaps the authors had this function from a previous undisclosed package?

# Findings {#sec-findings}

## Missing Requirements

- [X] Software Requirements 
  - [X] Stata
    - [ ] Version
    - Package for `splitvallabels`
  - [X] Python
    - [X] Version
- [X] Computational Requirements specified as follows:
  - Cluster size, disk size, memory size, etc.
- [X] Time Requirements 
  - Length of necessary computation (hours, weeks, etc.)

> [REQUIRED] Please amend README to contain complete requirements. 

You can copy the section above, amended if necessary.


## Data Preparation Code

## Tables and Figures

| Figure/Table # | Program               | Line Number | Reproduced?   |
|----------------|-----------------------|-------------|---------------|
| Figure 1       | Experimental material | -           | Not specified |
| Figure 2       | Experimental material | -           | Not specified |
| Figure 3       | Figure 3.do           | -           | Yes           |
| Table 1        | Table 1.do            | -           | Yes           |
| Figure 4       | Figure 4.do           | -           | Error         |
| Table 2        | Table 2.do            | -           | Yes           |
| Table 3        | Table 3.do            | -           | Yes           |
| Figure 5       | Figure 5.do           | -           | Yes           |
| Figure A.1     | Figure A1.ipynb       | -           | Not run       |
| Table B.1      | Table B1.do           | -           | Yes           |
| Figure B.2     | Figure B2.do          | -           | Yes           |
| Table C.2      | Table C2.do           | -           | Yes           |
| Table C.3      | Table C3.do           | -           | Yes           |
| Table C.4      | Table C4.do           | -           | Yes           |
| Table C.5      | Table C5.do           | -           | Yes           |
| Table C.6      | Table C6.do           | -           | Yes           |
| Table C.7      | Table C7.do           | -           | Yes           |
| Table C.8      | Table C8.do           | -           | Yes           |
| Table C.9      | Table C9.do           | -           | Yes           |
| Table C.10     | Table C10.do          | -           | Yes           |
| Table C.11     | Table C11.do          | -           | Yes           |
| Table D.3      | Figure 5.do           | -           | Yes           |
| Table D.4      | Figure D4.do          | -           | Not run       |
| Table D.12     | Table D12.do          | -           | Not run       |
| Table D.13     | Table D13.do          | -           | Not run       |
| Table D.14     | Table D14.do          | -           | Not run       |
| Figure D.5     | Figure 5.do           | -           | Not run       |
| Table D.15     | Table D15.do          | -           | Not run       |
| Table D.16     | Table D.16.do         | -           | Not run       |
| Figure D.6     | Figure D6.do          | -           | Not run       |
| Figure D.7     | Figure D7.do          | -           | Not run       |
| Figure E.8     | Experimental material | -           | Not specified |
| Table E.17     | Table E17.do          | -           | Not run       |
| Table E.18     | Table E18.do          | -           | Not run       |
| Table E.19     | Table E19.do          | -           | Not run       |
| Figure E.9     | Experimental material | -           | Not specified |
| Table E.20     | Table E20.do          | -           | Not run       |
| Figure E.10    | Experimental material | -           | Not specified |
| Figure E.11    | Figure E11.do         | -           | Not run       |
| Table E.21     | Table E21.do          | -           | Not run       |
| Table E.22     | Table E22.do          | -           | Not run       |
| Table E.23     | Table E23.do          | -           | Not run       |

All replicated figures and tables match the results of the manuscripts. Some figures could not be replicated due to the error reported above.

## In-Text Numbers

- [ ] In-text numbers not verified.

- [X] There are no in-text numbers, or all in-text numbers stem from tables and figures.

- [ ] There are in-text numbers, but they are not identified in the code

## Other Issues

- Scripts to automate package installation would be welcome, since this is the reason why reproduction of the results was partial.


# Classification

- [ ] full reproduction
- [ ] full reproduction with minor issues
- [X] partial reproduction (see above)
- [ ] not able to reproduce most or all of the results (reasons see above)

## Reason for incomplete reproducibility

- [ ] None.
- [ ] `Discrepancy in output` (either figures or numbers in tables or text differ)
- [ ] `Bugs in code` that were fixable by the replicator (but should be fixed in the final deposit)
- [ ] `Code missing`, in particular if it prevented the replicator from completing the reproducibility check
  - [ ] `Data preparation code missing` should be checked if the code missing seems to be data preparation code
- [X] `Code not functional` is more severe than a simple bug: it prevented the replicator from completing the reproducibility check
- [ ] `Software not available to replicator` may happen for a variety of reasons, but in particular (a) when the software is commercial, and the replicator does not have access to a licensed copy, or (b) the software is open-source, but a specific version required to conduct the reproducibility check is not available.
- [ ] `Insufficient time available to replicator` is applicable when (a) running the code would take weeks or more (b) running the code might take less time if sufficient compute resources were to be brought to bear, but no such resources can be accessed in a timely fashion (c) the replication package is very complex, and following all (manual and scripted) steps would take too long.
- [ ] `Data missing` is marked when data *should* be available, but was erroneously not provided, or is not accessible via the procedures described in the replication package
- [ ] `Data not available` is marked when data requires additional access steps, for instance purchase or application procedure. 
- [ ] `Missing README` is marked if there is no README to guide the replicator, or the README is not in compliance with JPE requirements


{{< include generated/report-pii.md >}}